name: Build packages

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Build LLVM
        run: |
          mkdir build
          cd build
          cmake ../llvm -DLLVM_ENABLE_PROJECTS=clang -DLLVM_TARGETS_TO_BUILD=host -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
          cmake --build . --config Release
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: installed-windows
          path: ./build/Release
